### ISSUE TITLE
Could not find existing command: Needs manual load after every reboot

### ISSUE THREAD

**Issue by lukechristy** [FlashyReese/CommandAliases#14]
During server boot it seems this mod gets loaded before the one its commands point-to. It requires me to type the load/reload command after every reboot to get it working. I realise this might be out of scope of your mod but any guidance would be greatly appreciated. It says this in the console on boot:
[https://i.imgur.com/aKTfLB0.png](https://i.imgur.com/aKTfLB0.png)

[
{
	"commandMode": "COMMAND_REDIRECT_NOARG",
	"command": "co",
	"redirectTo": "dl inspect"
}
]

**Comment by FlashyReese** [comment]
This would be an issue on Command Aliases, since the games registers Command Aliases' commands first due to alphabetical order of mod loading if I'm not mistaken, so it causes the issue where a command isn't found because it is registered after Command Aliases.

I will take a look into this when I have time.

**Comment by ghost** [comment]
A temporary solution would be to setup a scheduled running of the `/commandaliases load` command after your automatic restarts. Maybe about 5 minutes later to make sure the server is properly loaded,
